version: '2'
services:
  app:
    image: openjdk:8-jdk-alpine
    ports:
        - "8080:8080"
    volumes:
        - ./spring:/app
    working_dir: /app
    command: ./gradlew bootRun
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile-MySQL
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: condor
      TZ: "Asia/Tokyo"
    ports:
      - '3306:3306'
    volumes:
        - ./mysql:/mysql
