version: '2'
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-MySQL
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: condor
      TZ: "Asia/Tokyo"
    ports:
      - '3306:3306'
    volumes:
        - ./mysql:/mysql
