spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect:  org.hibernate.MySQL5Dialect
logging:
  file: logs/myapp.log
  level:
    org.springframework.web:  INFO
    jp.co.condor: DEBUG